In [1]:
import numpy as np

a = np.array([[0,0,0,0],[0,1,1,1],[0,0,0,0],[1,1,1,1]])
b = np.where(a == 1)
print(a)
print(b)
l = list(zip(b[0],b[1]))
for i in l:
    print(i)
print(a[l[0]])

[[0 0 0 0]
 [0 1 1 1]
 [0 0 0 0]
 [1 1 1 1]]
(array([1, 1, 1, 3, 3, 3, 3], dtype=int64), array([1, 2, 3, 0, 1, 2, 3], dtype=int64))
(1, 1)
(1, 2)
(1, 3)
(3, 0)
(3, 1)
(3, 2)
(3, 3)
1


In [2]:
list =[2,3,4]
list2 = [5,6]
list += list2
print(list)
print(a[0,0])

[2, 3, 4, 5, 6]
0


In [3]:
x = 1
0 < x < 2

True

In [4]:
list = [1,2,3]
list
dir = [1,1]
[1,1]+dir

[1, 1, 1, 1]

In [12]:
board_weight = [[1, 8, 3, 7, 7, 3, 8, 1], [8, 3, 2, 5, 5, 2, 4, 8], [3, 2, 6, 6, 6, 6, 2, 3], [7, 5, 6, 4, 4, 6, 5, 7], [
    7, 5, 6, 4, 4, 6, 5, 7], [3, 2, 6, 6, 6, 6, 2, 3], [8, 3, 2, 5, 5, 2, 4, 8], [1, 8, 3, 7, 7, 3, 8, 1]]
board_weight[::2]

[[1, 8, 3, 7, 7, 3, 8, 1],
 [3, 2, 6, 6, 6, 6, 2, 3],
 [7, 5, 6, 4, 4, 6, 5, 7],
 [8, 3, 2, 5, 5, 2, 4, 8]]

In [11]:
def A(**kwds):
    print(kwds)
squares = {(x, y) for x in range(8) for y in range(8)}
type(squares)
dict = {"a":"aaaaaaaaa", "b":"vvvvvvvvvvvvv"}
set(dict)

{'a', 'b'}

In [2]:
from numpy import average


ab = [0.03, 0.09, 0.09, 0.2, 0.41, 0.49, 0.78, 0.93, 0.72, 0.9, 0.35, 1.3, 0.3, 0.24, 0.4, 0.39, 0.54, 0.29, 0.7, 0.33, 0.78, 0.36, 0.63, 0.26, 0.0, 0.15, 0.39, 0.05, 0.32, 0.09, 0.07, 0.01, 0.0, 0.0, 0.0]
mm = [0.28, 0.38, 1.21, 1.37, 3.08, 1.21, 3.66, 6.74, 9.61, 15.37, 10.17, 14.66, 20.03, 5.08, 19.1, 9.53, 3.41, 10.89, 10.76, 13.43, 8.68, 9.83, 8.03, 7.38, 9.32, 3.98, 4.09, 8.53, 1.68, 3.78, 3.36, 0.0, 1.9, 1.35, 0.86, 0.15, 0.1, 0.0]
print(average(ab))
print(average(mm))

0.3597142857142857
6.1313157894736845
