# Numpy
Numpy is an extended python library including a lot of operations on matrix and mathematical function library.


In [94]:
# rename numpy as np for convenience
import numpy as np

## 1. Array/Matrix Creation

### 1.1 Converting Python sequences to NumPy Arrays
NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using [...] and (...), respectively. Lists and tuples can define ndarray creation:

- a list of numbers will create a 1D array,

- a list of lists will create a 2D array,

- further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.

In [95]:
# use a list to initialize a one-dimentional numpy array
arr=np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [96]:
type(arr)  # <class 'numpy.ndarray'>

numpy.ndarray

In [97]:
arr.itemsize #number of Bytes for each element, floating

4

In [166]:
arr = np.array([0,1,2,3,4,5], dtype='int16')  ## initialize with int type
arr.itemsize ## int type

2

In [99]:
arr.dtype    ## 'int16'

dtype('int16')

In [100]:
arrf = arr.astype('float32')
arr,arrf

(array([0, 1, 2, 3, 4, 5], dtype=int16),
 array([0., 1., 2., 3., 4., 5.], dtype=float32))

In [101]:
# use a list of lists to initialize a two-dimentional numpy array
arr2d = np.array([[1, 2], [3, 4]])
#use further nested lists to initialize a higher-dimensional arrays
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2d,arr3d

(array([[1, 2],
        [3, 4]]),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]))

### 1.2 Intrinsic NumPy array creation functions

#### 1D array creation functions
<hr>

**numpy.arange** creates arrays with regularly incrementing values.
<https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange>

In [102]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [104]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

Note: best practice for numpy.arange is to use integer start, end, and step values. There are some subtleties regarding dtype. In the second example, the dtype is defined. In the third example, the array is dtype=float to accommodate the step size of 0.1. Due to roundoff error, the stop value is sometimes included.
<hr>

**numpy.linspace** will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.
<https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace>

In [105]:
np.linspace(1., 4., 6)  # (4 - 1) / (6 - 1)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

#### 2D array creation functions

<hr>

**numpy.diag** can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements.

In [106]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [107]:
np.diag([1, 2, 3, 4], 1), np.diag([1,2,3,4], -1)

(array([[0, 1, 0, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 0, 0, 3, 0],
        [0, 0, 0, 0, 4],
        [0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]]))

In [108]:
a = np.array([[1, 2], [3, 4]])
a, np.diag(a)

(array([[1, 2],
        [3, 4]]),
 array([1, 4]))

In [109]:
np.identity(4, dtype=int)# identity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [110]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<hr>

#### General ndarray creation functions
The ndarray creation functions e.g. **numpy.ones**, **numpy.zeros**, and **numpy.full** define arrays based upon the desired shape. The ndarray creation functions can create arrays with any dimension by specifying how many dimensions and length along that dimension in a tuple or list.

In [111]:
# 构造全零矩阵
np.zeros((10,10), dtype=None)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [112]:
# 构造全一矩阵
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [113]:
#用指定数填充矩阵
np.full((4,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

The **random** method of the result of **default_rng** will create an array filled with random values between 0 and 1. It is included with the **numpy.random** library. Below, two arrays are created with shapes (2,3) and (2,3,2), respectively. The seed is set to 42 so you can reproduce these pseudorandom numbers:

In [114]:
from numpy.random import default_rng
default_rng(42).random((2,3)), default_rng(42).random((2,3,2))

(array([[0.77395605, 0.43887844, 0.85859792],
        [0.69736803, 0.09417735, 0.97562235]]),
 array([[[0.77395605, 0.43887844],
         [0.85859792, 0.69736803],
         [0.09417735, 0.97562235]],
 
        [[0.7611397 , 0.78606431],
         [0.12811363, 0.45038594],
         [0.37079802, 0.92676499]]]))

<hr>

#### Replicating, joining, or mutating existing arrays
Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly **numpy.copy** the array, otherwise the variable is a view into the original array. 

In [115]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]   # b指向a中内存，并没有重新开辟空间
b += 1
a,b

(array([2, 3, 3, 4, 5, 6]), array([2, 3]))

In above example, you did not create a new array. You created a variable, **b** that viewed the first 2 elements of a. When you added 1 to b you would get the same result by adding 1 to a[:2]. If you want to create a new array, use the numpy.copy array creation routine as such:

In [116]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2].copy()
b += 1
a,b

(array([1, 2, 3, 4, 5, 6]), array([2, 3]))

## 2. Array/Matrix Operations
### 2.1 Indexing on ndarrays


In [117]:
x = np.arange(10)
x, x[2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 2)

In [118]:
x.shape

(10,)

In [119]:
x.shape = (2,5)
x # x reshape from （10,） to （2,5）

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [120]:
# 两种形式都可
x[1,3],x[1][3]

(8, 8)

In [121]:
x[0]

array([0, 1, 2, 3, 4])

In [122]:

x[0:5:2] #slice, get from the first row to the 5th row with stepsize = 2


array([[0, 1, 2, 3, 4]])

In [123]:
x[-1] #slice, get last row

array([5, 6, 7, 8, 9])

In [124]:
x[:,0::2] #slice, get all row and columns from the first column to the last column with stepsize = 2

array([[0, 2, 4],
       [5, 7, 9]])

In [125]:
x,x[np.array([0, 1]), np.array([0, 2])] #get x[0,0] and x[1,2]

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([0, 7]))

In [126]:
x[np.array([0, 1]), 2]#broadcasting mechanism: get x[0,2] and x[1,2]

array([2, 7])

In [127]:
x.diagonal() # get the diagonal elements of x

array([0, 6])

In [128]:
x.diagonal(offset=1) # 向右偏移

array([1, 7])

In [129]:
x.diagonal(offset=-1) # 向下偏移

array([5])

In [130]:
np.diag(x), x.diagonal() # get the diagonal elements of x

(array([0, 6]), array([0, 6]))

In [131]:
i = np.arange(2)# get the diagonal elements of x
x[i,i]

array([0, 6])

### 2.2 Array manipulations
**numpy.tile(A, reps)**  
Construct an array by repeating A the number of times given by reps.

In [132]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [133]:
np.tile(a, 2) # 单个参数是横向复制

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [134]:
np.tile(a, (2, 2)) # 元组中第一个参数是纵向复制次数，第二个参数是横向复制次数

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [135]:
np.tile(a, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

**numpy.stack**  
Join a sequence of arrays along a new axis. Each array must have the same shape.

In [136]:
arrays = [np.random.randn(3, 4) for _ in range(5)]
arrays

[array([[-0.30705112, -1.91865997, -0.05752429, -0.58087323],
        [ 1.32151217,  1.12763893,  0.35083316,  0.49484952],
        [ 0.10971152, -0.21421381, -0.04679739,  0.65798272]]),
 array([[ 0.84644833,  0.43106752, -0.14990017,  0.60322715],
        [ 1.81888592, -0.23076343, -2.94435319, -0.51716791],
        [ 1.60685676, -1.29051715,  0.12084804,  0.25007494]]),
 array([[-0.69558958, -0.0102231 ,  0.1489995 ,  0.58224891],
        [ 1.69402265,  2.33601131, -0.10980592, -0.13670603],
        [ 1.07934839, -1.29552524,  0.8823561 ,  1.00226914]]),
 array([[-0.18663558, -1.55712182, -1.40287456, -1.3333593 ],
        [-1.20459413, -0.2314775 ,  0.12103126,  2.0787084 ],
        [ 0.72309117, -0.7020925 , -0.30420756, -0.08315357]]),
 array([[ 0.84282996,  0.19208197,  0.3887329 , -0.78618909],
        [ 0.82060105, -0.80882189,  1.40616961, -1.27623373],
        [ 0.19362746,  1.04780755, -0.89884896,  0.74674692]])]

In [137]:
np.stack(arrays, axis=0) #shape = (5, 3, 4)

array([[[-0.30705112, -1.91865997, -0.05752429, -0.58087323],
        [ 1.32151217,  1.12763893,  0.35083316,  0.49484952],
        [ 0.10971152, -0.21421381, -0.04679739,  0.65798272]],

       [[ 0.84644833,  0.43106752, -0.14990017,  0.60322715],
        [ 1.81888592, -0.23076343, -2.94435319, -0.51716791],
        [ 1.60685676, -1.29051715,  0.12084804,  0.25007494]],

       [[-0.69558958, -0.0102231 ,  0.1489995 ,  0.58224891],
        [ 1.69402265,  2.33601131, -0.10980592, -0.13670603],
        [ 1.07934839, -1.29552524,  0.8823561 ,  1.00226914]],

       [[-0.18663558, -1.55712182, -1.40287456, -1.3333593 ],
        [-1.20459413, -0.2314775 ,  0.12103126,  2.0787084 ],
        [ 0.72309117, -0.7020925 , -0.30420756, -0.08315357]],

       [[ 0.84282996,  0.19208197,  0.3887329 , -0.78618909],
        [ 0.82060105, -0.80882189,  1.40616961, -1.27623373],
        [ 0.19362746,  1.04780755, -0.89884896,  0.74674692]]])

In [138]:
np.stack(arrays, axis=2) # shape = (3 ,4 , 5)

array([[[-0.30705112,  0.84644833, -0.69558958, -0.18663558,
          0.84282996],
        [-1.91865997,  0.43106752, -0.0102231 , -1.55712182,
          0.19208197],
        [-0.05752429, -0.14990017,  0.1489995 , -1.40287456,
          0.3887329 ],
        [-0.58087323,  0.60322715,  0.58224891, -1.3333593 ,
         -0.78618909]],

       [[ 1.32151217,  1.81888592,  1.69402265, -1.20459413,
          0.82060105],
        [ 1.12763893, -0.23076343,  2.33601131, -0.2314775 ,
         -0.80882189],
        [ 0.35083316, -2.94435319, -0.10980592,  0.12103126,
          1.40616961],
        [ 0.49484952, -0.51716791, -0.13670603,  2.0787084 ,
         -1.27623373]],

       [[ 0.10971152,  1.60685676,  1.07934839,  0.72309117,
          0.19362746],
        [-0.21421381, -1.29051715, -1.29552524, -0.7020925 ,
          1.04780755],
        [-0.04679739,  0.12084804,  0.8823561 , -0.30420756,
         -0.89884896],
        [ 0.65798272,  0.25007494,  1.00226914, -0.08315357,
          0

In [139]:
a = np.arange(5)
np.vstack([a,x]) #append a to x as the first row

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [140]:
np.vstack([x,a]) #append a to x as the last row

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [141]:
a = np.arange(10).reshape(2,5)
np.r_[x,a] #similar with np.vstack(), but all the input array dimensions for the concatenation axis must match exactly

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [142]:
b = np.arange(2).reshape(2,1)
np.hstack([b,x]) #append b to x as the first column

array([[0, 0, 1, 2, 3, 4],
       [1, 5, 6, 7, 8, 9]])

In [143]:
np.hstack([x,b]) #append b to x as the last column

array([[0, 1, 2, 3, 4, 0],
       [5, 6, 7, 8, 9, 1]])

In [144]:
np.c_[x, a] # #similar with np.hstack(), but all the input array dimensions for the concatenation axis must match exactly

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [145]:
x[x > 5] # get elements that are bigger than 5

array([6, 7, 8, 9])

In [146]:
y = x.copy() # set the elements that are bigger than 5 to 10
y[x > 5] = 10
y[x <= 5] = 0
y

array([[ 0,  0,  0,  0,  0],
       [ 0, 10, 10, 10, 10]])

In [147]:
np.argmax(x) #Returns the indices of the maximum values

9

In [148]:
np.argmax(x, axis=0)#Returns the indices of the maximum values along an axis.

array([1, 1, 1, 1, 1], dtype=int64)

In [149]:
np.argmax(x, axis=1)#Returns the indices of the maximum values along an axis.

array([4, 4], dtype=int64)

In [150]:
np.argmin(x) #Returns the indices of the minimum values

0

In [151]:
np.argmin(x, axis=0) #Returns the indices of the minimum values along an axis.

array([0, 0, 0, 0, 0], dtype=int64)

In [152]:
np.argmin(x, axis=1)

array([0, 0], dtype=int64)

In [153]:
x, np.argwhere(x>5) #

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[1, 1],
        [1, 2],
        [1, 3],
        [1, 4]], dtype=int64))

In [154]:
np.nonzero(x>5),np.transpose(np.nonzero(x>5))

((array([1, 1, 1, 1], dtype=int64), array([1, 2, 3, 4], dtype=int64)),
 array([[1, 1],
        [1, 2],
        [1, 3],
        [1, 4]], dtype=int64))

**numpy.where**  
numpy.where(condition, [x, y, ]/)  
return an array with elements from x where condition is True, and elements from y elsewhere.

In [155]:
x, y = np.ogrid[:3, :4]
print(x, y)
z = np.where(x < y, x, 10 + y)
z

[[0]
 [1]
 [2]] [[0 1 2 3]]


array([[10,  0,  0,  0],
       [10, 11,  1,  1],
       [10, 11, 12,  2]])

In [156]:
np.where(z < 10, 0, 10)

array([[10,  0,  0,  0],
       [10, 10,  0,  0],
       [10, 10, 10,  0]])

**numpy.sort(a, axis=- 1, kind=None, order=None)**

Return a sorted copy of an array.

In [157]:
x = np.array([5, 4, 6, 8, 1, 2, 9])
print('x:', x)
x.sort()
print('x:', x)

x: [5 4 6 8 1 2 9]
x: [1 2 4 5 6 8 9]


In [163]:
x = np.array([[7, 5, 8], [9, 6, 4], [3, 4, 9]])
print('x:\n', x)
x.sort(axis=0) # axis=0按列排序，axis=1按行排序
print('x:\n', x)

x:
 [[7 5 8]
 [9 6 4]
 [3 4 9]]
x:
 [[3 4 4]
 [7 5 8]
 [9 6 9]]


**numpy.argsort(a, axis=- 1, kind=None, order=None)**

Returns the indices that would sort an array.

In [65]:
x = np.array([5, 4, 6, 8, 1, 2, 9])
print('arr:\n', x)
x_index = np.argsort(x)
print('x:\n', x)
print('x_index:\n', x_index)

arr:
 [5 4 6 8 1 2 9]
x:
 [5 4 6 8 1 2 9]
x_index:
 [4 5 1 0 2 3 6]


In [164]:
x = np.array([[7, 5, 8], [9, 6, 4], [3, 4, 9]])
print('x:\n', x)
x_index = np.argsort(x, axis=-1)
print('x_index:\n', x_index)

x:
 [[7 5 8]
 [9 6 4]
 [3 4 9]]
x_index:
 [[1 0 2]
 [2 1 0]
 [0 1 2]]


### 2.3 mathematical operators

In [67]:
x = np.arange(10).reshape(2,5)
x + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [68]:
x + x

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [69]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [70]:
x ** 2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [71]:
x ** (1/2)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [72]:
x.T # 矩阵转置

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [73]:
x.transpose() # same with x.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [74]:
np.max(x) # 

9

In [75]:
np.max(x,axis=0) # the maximum value in each column

array([5, 6, 7, 8, 9])

In [76]:
np.max(x,axis=1) # the maximum value in each row

array([4, 9])

In [77]:
np.sum(x)

45

In [78]:
np.sum(x,axis=0) # the sum of each column

array([ 5,  7,  9, 11, 13])

In [79]:
np.sum(x,axis=1) # the sum of each row

array([10, 35])

In [80]:
np.mean(x)

4.5

In [81]:
np.mean(x, axis=0)# the mean of each column

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [82]:
np.mean(x, axis=1)# the mean of each row

array([2., 7.])

In [83]:
np.var(x) # variance value

8.25

In [84]:
np.std(x)# standard deviation value

2.8722813232690143

In [85]:
x1 = np.array([2j, 3j])
x2 = np.array([2j, 3j])
np.matmul(x1,x2) # Matrix product of two arrays.

(-13+0j)

In [86]:
x1 @ x2 #The @ operator can be used as a shorthand for np.matmul on ndarrays.

(-13+0j)

In [87]:
np.multiply(x1,x2) # Multiply arguments element-wise.

array([-4.+0.j, -9.+0.j])

In [88]:
x1 * x2 #The * operator can be used as a shorthand for np.multiply on ndarrays.

array([-4.+0.j, -9.+0.j])

## 3. Reading array from file and writing to file

In [89]:
np.savetxt('1.txt', x, fmt='%d', delimiter=',') # save an array to 1.txt with format %d

In [90]:
np.genfromtxt('1.txt',delimiter=',')    ## get an array from 1.txt

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])