## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [2]:
import numpy as np

In [3]:
#1
mat0 = np.zeros((10,10))
mat0[0,:] = mat0[9, :] = mat0[:, 0] = mat0[:, 9] = 1
mat0

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [4]:
#2
arr0 = np.array([0,1,2,3,4])
np.tile(arr0,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [5]:
#3
mat1 = np.array([[0,1],[1,0]], dtype=float)
np.tile(mat1,(4,4))


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [6]:
#4
arr1 = np.array([0,1,2,3,4,5,6,7,8,9])
arr1[1::2]

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix 

In [18]:
#5
from sklearn.preprocessing import normalize
mat2 = np.random.randn(5, 5)
normalize(mat2,norm='max')

array([[ 1.        ,  0.20689163, -0.58211354,  0.34230346, -0.18467004],
       [-0.16944161,  0.34605905,  0.5885229 , -1.        , -0.07775171],
       [-0.04986419,  0.15170873,  1.        , -0.28866   , -0.61305046],
       [ 0.60281551, -1.        , -0.43098151, -0.66686656,  0.25533882],
       [-1.        ,  0.13937296,  0.40849323, -0.36518181, -0.31903148]])

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [28]:
#6
import math
print('X, Y:')
mat3 = [np.random.randn(2, 10)]
print(mat3[0][0]) 
print(mat3[0][1])
R = []
T = []

for x, y in zip(mat3[0][0], mat3[0][1]):
    R.append(np.sqrt(x*x+y*y))
    T.append(np.arctan(y/x)/math.pi)
print('R:')
print(R)
print('T:')
print(T)

X, Y:
[ 1.49484053  0.62098856  0.57397549 -1.71298434 -0.26134529 -0.28813399
 -1.66052595  0.1167016  -0.81813924  0.7104764 ]
[ 1.06439602 -0.2034386  -0.12270125  0.045049   -0.02631653  0.34393921
 -0.20212828 -1.34002501 -1.06211596 -0.70123257]
R:
[1.8350714095801783, 0.6534631288840302, 0.5869441753628056, 1.71357659685904, 0.26266693995646107, 0.44868181891305303, 1.672782793982801, 1.3450971255578708, 1.3406871872147346, 0.9982503886665531]
T:
[0.1969590854912909, -0.10077235909864278, -0.06703746117293859, -0.00836915781267064, 0.03194497502958263, -0.2780306318287079, 0.038556729639644474, -0.4723484399891261, 0.2910735202890524, -0.24791574588771345]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [49]:
#7
arr3 = np.array([1,2,3,4,5])
mat4 = np.zeros((3,5), dtype=int)
mat5 = np.vstack([arr3,mat4])
arr4 = mat5.flatten('f')
arr4[:-3]

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [52]:
#8 因为nan不是一个数，所以相关计算都无法得到数字。所有涉及nan的操作，返回的都是nan
print('0 * np.nan =',0 * np.nan)

print('np.nan == np.nan:',np.nan == np.nan)

print('np.inf > np.nan:',np.inf > np.nan)

print('np.nan - np.nan =',np.nan - np.nan)

print('np.nan in set([np.nan]):',np.nan in set([np.nan]))

print('0.3 == 3 * 0.1:',0.3 == 3 * 0.1)

0 * np.nan = nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan = nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [60]:
#9
print(np.array(0) / np.array(0)) # 出现0除以0的情况
print(np.array(0) // np.array(0)) # 被除数为0的警告
#根据IEEE标准，NaN二进制表示为全1，所以转换为int型后，
#变为负的最大值-2147483648，再转为float类型-2.14748365e+09
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-2.14748365e+09]


C:\Users\21621\AppData\Local\Temp\ipykernel_27600\1134272783.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\21621\AppData\Local\Temp\ipykernel_27600\1134272783.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [64]:
np.array([np.nan]).astype(int)

array([-2147483648])